layout_spectrum: 0.701064
typography_spectrum: 0.9147926
color:
  saturation: 0.8234364
  lightness: 0.9841906
  brandStrength: 0.3621892
  rhythmicContrast: 0.7423936
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
name: Onurataman
